use_frameworks!

platform :ios, '10.0'

target 'VocLiveChatFramework_Example' do
  pod 'VocLiveChatFramework', :path => '../'

  target 'VocLiveChatFramework_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
